### ISSUE TITLE
Consider bumping Cake.CK.Pack minor version: e.g. 0.10.0 instead of 0.9.1

### ISSUE THREAD

**Issue by augustoproiete** [Invenietis/CK-Globbing#3]
Just a small note/suggestion as I just noticed the Cake.CK.Pack 0.9.1 release:

Cake.CK.Pack v0.9.0 targets Cake >= v0.**37**.0, and the recently released Cake.CK.Pack v0.9.1 targets Cake >= v0.**38**.5.

Given that there was a minor version bump of the Cake targeted (37 -> 38), it would be a good practice to also bump the minor version of the Cake.CK.Pack addin, instead of bumping the patch version. i.e. 0.10.0 instead of 0.9.1

I'd suggest releasing a new Cake.CK.Pack package version 0.10.0 and [unlisting](https://docs.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages#unlisting-a-package) version 0.9.1 from nuget.org

**Comment by olivier-spinelli** [comment]
Good catch!
We missed this version bump because of this semver spec: https://semver.org/#spec-item-4.
This 0 major is actually a case that is somehow skipped by the tool we are now using to release all our libraries: https://github.com/CK-Build/CKli.
However, I think you're right: a Minor bump (of a 0 major) should be propagated (as a feature-change impact) to its dependencies. I'm planning to take this into account in CKli so that this won't happen again.
So thank you !
If the current labelling (0.9.1 instead of 0.10.0) really annoys you (tooling, automated checker or whatever reason), I'll release a new one: just tell me (I keep this isuue opened).

**Comment by augustoproiete** [comment]
Cheers @olivier-spinelli. No rush on this one (from my end anyway, as I'm already on Cake 0.38.*, so nothing breaks with this upgrade). I just thought I'd put this on your radar after I noticed it.

**Comment by augustoproiete** [comment]
Closing this now that 0.10.0 has been released https://www.nuget.org/packages/Cake.CK.Pack/0.10.0

Docs: https://cakebuild.net/extensions/cake-ck-pack/
